# Generated by Django 5.0.7 on 2024-08-05 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0004_user_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
