# Generated by Django 5.0.7 on 2024-08-05 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0005_otp_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='uuid',
        ),
        migrations.AlterField(
            model_name='otp',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
