# Generated by Django 4.2.6 on 2024-08-06 07:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0006_remove_user_uuid_alter_otp_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=6, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='user_images/')),
                ('age', models.CharField(choices=[('INF', 'Infants (0-2 years)'), ('TOD', 'Toddlers (2-4 years)'), ('CHI', 'Children (5-12 years)'), ('TEEN', 'Teenagers (13-19 years)'), ('YAD', 'Young Adults (20-35 years)'), ('MAD', 'Middle-Aged Adults (36-55 years)'), ('SEN', 'Seniors (56-75 years)'), ('ELD', 'Elderly (76+ years)')], default='YAD', max_length=5)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
